name: Build .NET

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'  # Prevent running on workflow file updates

jobs:
  build:
    name: Build and Release Executables
    runs-on: ubuntu-latest  # Only run on Ubuntu

    strategy:
      matrix:
        target: [win-x64, linux-x64, osx-x64]  # Build for different platforms

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x  # Change based on your project

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Publish executable for ${{ matrix.target }}
        run: dotnet publish -c Release -r ${{ matrix.target }} --self-contained true -o ./build/${{ matrix.target }}

      - name: Zip build files
        run: |
          cd build/${{ matrix.target }}
          zip -r ../../chess-engine-${{ matrix.target }}.zip .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: chess-engine-${{ matrix.target }}
          path: chess-engine-${{ matrix.target }}.zip
