on:
  push:
    branches:
      - master
      - main

name: Copy Ubuntu Release To Lichess-Bot Repo

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Copy the publish folder
      - name: Push ubuntu release
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "bin/Release/net7.0/ubuntu.16.04-x64/publish/"
          destination_repo: "Nateml/lichess-bot"
          destination_folder: "engines/ChessBot/"
          destination_branch: "master"
          user_email: "nateml.mac@gmail.com"
          user_name: "Nateml"
          commit_message: "AUTO: Copying ubuntu build from Nateml/ChessBot"
          git_server: "github.com"
          
      
